config/routes.rb
Forsyth::Application.routes.draw do
  resources :orders

  get "rssfeed/index"

  resources :line_items

  resources :carts

  get "store/index"

  resources :products

  get "home/index"

  match 'about' => 'home#about'
  match 'store' => 'store#index'

  

   root :to => 'home#index'
   

  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  validates :title, :description, :image_url, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.00}
	validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
   	with: %r{\.(gif|jpg|png)$}i,
   	message: 'must be a URL for GIF, JPG or PNG image.'
   	}
   	
private

# ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
    return true
    else
    errors.add(:base, 'Line Items present')
    return false
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json

  
  def index
    @products = Product.all
    @cart = current_cart
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @cart = current_cart

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @cart = current_cart

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
     @cart = current_cart
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 8 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
 <div class="field">
    <%= f.label :preview %><br />
    <%= f.text_area :preview %>
  </div>
 <div class="field">
    <%= f.label :is_featured %><br />
    <%= f.check_box :is_featured %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container-fluid">
<div class="row-fluid">
<div class="span2">
&nbsp;
</div>

	<div class="span8">
	<div class="hero-unit">
	
	<h3>Editing product</h3>

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>

</div>
</div>
<div class="span2">
&nbsp;
</div>

app/views/products/index.html.erb
<div class="navbar navbar-fixed-top">
     <div class="navbar-inner">
       <div class="container-fluid">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </a>
         <a class="brand" href="#">Stuart Forsyth > Catalogue</a>
         <div class="nav-collapse">
           <ul class="nav">
             <li class="active"><a href="/">Home</a></li>
             <li><%= link_to "About", about_path %></li>
             </ul>
           <p class="navbar-text pull-right">Logged in as <a href="#">username</a></p>
         </div><!--/.nav-collapse -->
       </div>
     </div>
</div>

<div class-"container">

	<h1>Listing products</h1>

	<table>
	 	<% @products.each do |product| %>
	 	<tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >

	 	<td>
	 	<%= image_tag(product.image_url, class: 'list_image') %>
	 	</td>

	 	<td class="list_description" >
	 	<dl>
	 	<dt><%= product.title %></dt>
	 	<dd><%= truncate(strip_tags(product.description),
	 	length: 80) %></dd>
	 	</dl>
	 	</td>

	 	<td class="list_actions" >
	 	<%= link_to 'Show', product %><br />
	 	<%= link_to 'Edit', edit_product_path(product) %><br />
	 	<%= link_to 'Destroy', product,
	 	confirm: 'Are you sure?',
	 	method: :delete %>
	 	</td>
	 	</tr>
	 	<% end %>
	 	</table>

	<br />

	<%= link_to 'New Product', new_product_path %>


</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="hero-unit">
	<p id="notice"><%= notice %></p>

	<h1><%= @product.title%></h1>
	<p><%= image_tag(@product.image_url, :style => "float:left;padding:10px;") %><%= sanitize(@product.description)%></p>


	<p>
	<b>Price:</b>
	<%= number_to_currency(@product.price) %> <br/>
	<%= button_to 'Add to Cart', line_items_path(product_id: @product), remote:true %>
	</p>
	<p>
	<a href="https://twitter.com/share" class="twitter-share-button" data-text="<%= @product.title%>" data-via="s2rt" data-size="large">Tweet</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	</p>

	<%= link_to 'Edit', edit_product_path(@product) %> |
	<%= link_to 'Back', products_path %>
</div>